### ISSUE TITLE
No fill of Attributes

### ISSUE THREAD

**Issue by h2o-commits** [adamzammit/LTIPlugin#1]
Thanx for programming this plugin. I use it with Moodle and a Limesurvey Docker-Image. 

After switching to HTTPS i changed $_SERVER['HTTP_HOST'] to the real URL (not localhost)

I can take the survey und it gets saved. - But no Informationen gets saved to der 4 additional attributes. I can only  get access to the survey more than ones.

**Comment by adamzammit** [comment]
I have tested this plugin with Moodle and it works fine for me.

How are you accessing the survey from Moodle? It should be "Add an activity or resource" and then "External tool" and enter in the URL, key and secret that is generated on the plugin settings page in LimeSurvey.

Please also confirm you haven't changed any of the default attribute names that appear in the configuration  settings for the plugin in LimeSurvey

**Comment by h2o-commits** [comment]
Thank you for this fast reply! After confirming the default attributes it worked like a charm!

You might want to advertise the limesurvey integration in Moodle. :)
