### ISSUE TITLE
__construct() must be an instance of SimpleXMLElement, bool given

### ISSUE THREAD

**Issue by angonz** [adamzammit/LTIPlugin#2]
Hi!
I got this error when trying to upload the plugin with the upload facility:

> 500: Internal Server Error
> Argument 1 passed to ExtensionConfig::__construct() must be an instance of SimpleXMLElement, bool given, called in /opt/bitnami/apache/htdocs/application/models/ExtensionConfig.php on line 162
> 

I tried uploading to the plugins directory manually but it didn't recognize the plugin either.

I'm using Release 5.3.14 of LimeSurvey

**Comment by adamzammit** [comment]
I can't replicate this exactly but I did get an error when uploading the plugin downloaded from here: https://github.com/adamzammit/LTIPlugin/releases/download/1.0.8/LimeSurvey-LTIPlugin-1.0.8.zip in the latest version of LimeSurvey.

Please try downloading that zip file, extracting it locally then re-zipping it but moving all the files from the default sub directory to the root of the zip -  and see how you go

**Comment by angonz** [comment]
It worked!!! Thanks
