### ISSUE TITLE
Error while activating survey: Illegal offset type in isset or empty

### ISSUE THREAD

**Issue by adia** [adamzammit/LTIPlugin#4]
Hello! We have successfully used your plugin in the past to integrate a survey via LTI with the Open eClass LMS. I can see from backups that the LimeSurvey instance we used was version 4.6.2+210512, with LTIPlugin version 1.0.5, but unfortunately that server isn't currently online.

We have just setup a new LimeSurvey instance, version 5.6.9+230306 with LTIPlugin 1.1.0, and while initially everything went fine, when activating the survey via LTI the following error appears:

500: Internal Server Error
Illegal offset type in isset or empty
An internal error occurred while the Web server was processing your request. 

The new server is running Apache with mod_php (we tried PHP 8.0, 8.1 and 8.2 with the same result).

It seems the exception is caught and full details don't appear in the logs (is there a way to enable full error logging in LimeSurvey?) but by adding a line to print $exception->getTraceAsString() in vendor/yiisoft/yii/framework/base/CErrorHandler.php I captured the following backtrace, in case it helps:

```
#0 [internal function]: LTIPlugin->newDirectRequest()
#1 /var/www/html/limesurvey/application/libraries/PluginManager/PluginManager.php(269): call_user_func()
#2 /var/www/html/limesurvey/application/controllers/PluginsController.php(47): LimeSurvey\PluginManager\PluginManager->dispatchEvent()
#3 [internal function]: PluginsController->actionUnsecure()
#4 /var/www/html/limesurvey/vendor/yiisoft/yii/framework/web/actions/CAction.php(115): ReflectionMethod->invokeArgs()
#5 /var/www/html/limesurvey/vendor/yiisoft/yii/framework/web/actions/CInlineAction.php(47): CAction->runWithParamsInternal()
#6 /var/www/html/limesurvey/vendor/yiisoft/yii/framework/web/CController.php(308): CInlineAction->runWithParams()
#7 /var/www/html/limesurvey/vendor/yiisoft/yii/framework/web/CController.php(286): CController->runAction()
#8 /var/www/html/limesurvey/vendor/yiisoft/yii/framework/web/CController.php(265): CController->runActionWithFilters()
#9 /var/www/html/limesurvey/vendor/yiisoft/yii/framework/web/CWebApplication.php(282): CController->run()
#10 /var/www/html/limesurvey/vendor/yiisoft/yii/framework/web/CWebApplication.php(141): CWebApplication->runController()
#11 /var/www/html/limesurvey/vendor/yiisoft/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /var/www/html/limesurvey/index.php(192): CApplication->run()
#13 {main}
```

I also tested it through an LTI activity in Moodle and got the same error.

We'll continue trying to debug the problem, but I'd be grateful for any ideas or a possible solution - thanks in advance!

**Comment by adia** [comment]
So, I tried enabling debug mode and saw the following output:

```
string(20) "Valid LTI Connection"
 ----------------------------- 
array(27) {
  ["user_id"]=>
  string(1) "2"
  ["roles"]=>
  string(7) "Learner"
  ["resource_link_id"]=>
  string(26) "eclass-ine.gunet.gr:poll:1"
  ["resource_link_title"]=>
  string(18) "Test Questionnaire"
  ["resource_link_description"]=>
  string(18) "Test questionnaire"
  ["lis_person_name_full"]=>
  string(9) "Test User"
  ["lis_person_name_family"]=>
  string(4) "User"
  ["lis_person_name_given"]=>
  string(4) "Test"
  ["lis_person_contact_email_primary"]=>
  string(16) "adia+test@uoa.gr"
  ["context_id"]=>
  string(21) "eclass-ine.gunet.gr:1"
  ["context_title"]=>
  string(11) "Test Course"
  ["context_label"]=>
  string(6) "INE101"
  ["context_type"]=>
  string(13) "CourseSection"
  ["lis_course_section_sourcedid"]=>
  string(21) "eclass-ine.gunet.gr:1"
  ["launch_presentation_locale"]=>
  string(2) "el"
  ["launch_presentation_document_target"]=>
  string(6) "window"
  ["launch_presentation_return_url"]=>
  string(42) "https://eclass-ine.gunet.gr/courses/INE101"
  ["tool_consumer_info_product_family_code"]=>
  string(10) "openeclass"
  ["tool_consumer_info_version"]=>
  string(8) "3.14-dev"
  ["tool_consumer_instance_name"]=>
  string(12) "INE API Test"
  ["tool_consumer_instance_guid"]=>
  string(19) "eclass-ine.gunet.gr"
  ["tool_consumer_instance_description"]=>
  string(45) "Ακαδημαϊκό Διαδίκτυο GUNet"
  ["lti_version"]=>
  string(7) "LTI-1p0"
  ["lti_message_type"]=>
  string(24) "basic-lti-launch-request"
  ["oauth_consumer_key"]=>
  string(32) "JOFWoWtvzLToUYxLBtvxgVlsK7GiIwaG"
  ["plugin"]=>
  string(9) "LTIPlugin"
  ["function"]=>
  string(6) "791289"
}

```

Then tried disabling and re-enabling the survey and now it's working! Not sure what happened, the only other thing I changed was to add a description on the LMS side, seeing that empty string for "resource_link_description" - but even if I delete the description or create a new LTI questionnaire, it's still working perfectly.

I'll leave this issue open for now if you want me to investigate or test anything, otherwise feel free to close it. Thanks again!

**Comment by adamzammit** [comment]
Thanks for following up with this @adia 

From the debug you provided I can't see anything specific in the plugin that would cause this error.

I'll close this issue for now but please reopen it if you notice the error again - hopefully then we can reproduce and debug.
